# Generated by Django 5.1.5 on 2025-01-18 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source_name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'DataSource',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ObjectType',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UnitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_category_name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'UnitCategory',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ObjectInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_instance_name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.objecttype')),
            ],
            options={
                'db_table': 'ObjectInstance',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ObjectTypeProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type_property_name', models.CharField(max_length=255)),
                ('alarm_priority', models.IntegerField(blank=True, null=True)),
                ('alarm_enabled', models.BooleanField(default=False)),
                ('alarm_sounds_enabled', models.BooleanField(default=False)),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.objecttype')),
            ],
            options={
                'db_table': 'ObjectTypeProperty',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SubDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_data_source_name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.datasource')),
            ],
            options={
                'db_table': 'SubDataSource',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_enabled', models.BooleanField(default=False)),
                ('alarm_priority', models.IntegerField(blank=True, null=True)),
                ('log_alarm', models.BooleanField(default=False)),
                ('log_trigger_condition_change', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('object_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.objectinstance')),
                ('object_type_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.objecttypeproperty')),
                ('sub_data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subdatasource')),
            ],
            options={
                'db_table': 'DataSet',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type_name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('unit_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.unitcategory')),
            ],
            options={
                'db_table': 'UnitType',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UnitDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_definition_name', models.CharField(max_length=255)),
                ('scale_factor', models.FloatField()),
                ('offset', models.FloatField()),
                ('precision', models.IntegerField()),
                ('alias_text', models.CharField(max_length=255)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('calculation_method', models.TextField(blank=True, null=True)),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.unittype')),
            ],
            options={
                'db_table': 'UnitDefinition',
                'ordering': ['-id'],
            },
        ),
    ]
